<prog>      = expr (<whitespace> expr)*
whitespace  = #'\s+'
<value>     = integer | decimal | boolean
integer     = digit+
boolean     = 'true' | 'false'
decimal     = #'[0-9]+\.[0-9]+'
<digit>     = #'[0-9]'
<letter>    = #'[a-zA-Z]'
<alphanum>  = letter | digit
<expr>      = lambda | value | <'('> expr <')'>
lambda      = <'λ'> <whitespace> name <whitespace> <'.'> <whitespace> body
<body>      = expr
name        = letter alphanum*
